### PR TITLE
Changes to copy artifacts into multiple regions to support multi-region deployments. fixes #708

### LINKED ISSUE #708: [Feature Request] Adding multi-region deployment support to QS artifact bucket
Currently, taskcat supports multiple region testing. But when a customer has multi-region deployment, there is no way to specify in which regions artifacts needs to be uploaded, it will upload the artifacts in the same region where it is testing the deployment. In multi region deployment using StackSets, resources(especially, ones which can't call cross region buckets) failed to get deployed in regions other than the test region. And if one includes multiple regions in a single test then taskcat execute tests in parallel across multiple regions, and fails due to duplicate resource deployments.

If we add one more config setting artifact_regions to tests and still carry out testing from one region which handles multi region deployment.

example for resources which can't call cross region buckets: aws/aws-sam-cli#2807.

This feature should solve any resource which needs same region artifacts access

### PR DESCRIPTION
**Pull request by veeragoni**
…i-region deployments support. fixes #708

## Overview

Currently, taskcat supports multiple region testing. But when a customer has multi-region deployment, there is no way to specify in which regions artifacts needs to be uploaded, it will upload the artifacts in the same region where it is testing the deployment. In multi region deployment using StackSets, resources(especially, ones which can't call cross region buckets) failed to get deployed in regions other than the test region. And if one includes multiple regions in a single test then taskcat execute tests in parallel across multiple regions, and fails due to duplicate resource deployments.

If we add one more config setting artifact_regions to tests and still carry out testing from one region which handles multi region deployment.

example for resources which can't call cross region buckets: aws/aws-sam-cli#2807.

This feature should solve any resource which needs same region artifacts access

## Testing/Steps taken to ensure quality
ran pre-commit. didnt change any existing code quality. 

How did you validate the changes in this PR?

Tested it via taskcat CLI. worked like a champ.

### Notes

Optional. Caveats, Alternatives, Other relevant information.

## Testing Instructions

```
tests:
  default:
    template: ./templates/master-org.template.yaml
    artifact_regions:
      - us-east-1
      - us-east-2
    regions:
     - us-east-1
```
In this case the artifacts are copied to both east-1 and 2 and the us-east-1 deployment handles the multi region deployment internally where resources have access to respective buckets in the local region.

 How to test this PR Start after checking out this branch (bulleted)
 * Include test case, and expected output

### CODE REVIEW

**Review by andrew-glenn — CHANGES_REQUESTED** [review]
Artifacts are already copied to multiple regions via taskcat regional buckets.

Ex: `tcat-<hash>-<region_name>`, exposed via the `$[taskcat_autobucket]` psuedo-parameter. Unless I'm not identifying a new use-case, this can be solved via existing mechanisms and proper CFN logic.

**Comment by himanshu219** [comment]
@andrew-glenn  tcat-<hash>-<region_name>, exposed via the $[taskcat_autobucket] psuedo-parameter doesn't help in case of multi region deployment using stackset because since the test is running on say us-east-1 then taskcat_autobucket returns the bucket for that region only and stackset is deploying resources in another region say us-east-2, so there is no way to reference the bucket in us-east-2. Therefore one needs to have separate artifact and test regions.

**Review by andrew-glenn — APPROVED** [review]

**Pull request merged**
